### ISSUE TITLE
Start using bundle for images and all resources...(for cocoapods)

### ISSUE THREAD

**Issue by luka1995** [nicklockwood/CountryPicker#33]
http://stackoverflow.com/questions/25402782/cocoapodsresource-bundle-not-accessbile

**Comment by nicklockwood** [comment]
You should be able to load these on iOS using

    <Image source={{uri: 'BundleName/ImageName.png}}/>

If that doesn't work, there is a PR waiting that adds explicit support for bundles.

**Comment by astanton** [comment]
How can I get the images to work with the CocoaPod?  I just see the text in the UIPickerView.

**Comment by nicklockwood** [comment]
Is this fixed now?
